config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  resources :users, only: %i[new create show] do
    resources :attendees, only: [:index, :show]
    resources :events do
      resources :attendees, only: [:new,:create,:show, :destroy]
    end
  end

  resources :events, only: [:show] do
    resources :attendees, only: [:edit, :update]
  end

  get '/invites', to: 'attendees#create'
  post '/invites', to: 'attendees#create'
  get '/invitesdel', to: 'attendees#destroy'
  post '/invitesdel', to: 'attendees#destroy'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = User.find(params[:user_id])
    case params[:time_spec]
    when 'normal'
      @attendees = @user.attendees
    when 'future'
      @attendees = @user.attendees.select { |item| item.event.date > Time.now }
    when 'past'
      @attendees = @user.attendees.select { |item| item.event.date < Time.now }
    end
  end

  def create
    @user = User.find_by(username: params[:username])
    @event = Event.find(params[:event_id])
    @attendees = @event.attendees.find_by(user_id: @user.id)
    current_user = User.find(session[:user_id])
    if @user.nil?
      redirect_to event_path(@event.id)
      flash[:notice] = 'That user does not exist.'
    elsif params[:username] == current_user.username
      redirect_to event_path(@event.id)
      flash[:notice] = 'Thats yourself!!'
    elsif @attendees.nil? || @attendees.status == 'canceled'
      @attendee = @event.attendees.create(status: 'pending', user_id: @user.id)
      redirect_to event_path(@event.id)
      flash[:notice] = "Invitation sent to #{@user.username}"
    else
      redirect_to event_path(@event.id)
      flash[:notice] = 'That user already have an invitatin for this event'
    end
  end

  def destroy
    @attendee = Attendee.find(params[:id])
    @attendee.destroy
    redirect_to event_path(params[:event_id])
  end

  def update
    @attendee = Attendee.find(params[:id])
    if @attendee.update(status: attemdee_params)
      check_event(@attendee.event_id)
      redirect_to event_path(@attendee.event.id)
      flash[:notice] = 'Invitation updated'
    else
      redirect_to event_path(@attendee.event.id)
      flash[:notice] = 'Invitation cant be updated'
    end
  end

  private

  def check_event(event_id)
    @event = Event.find(event_id)
    @attendees = @event.attendees
    if @event.tpeople == @attendees.count
      @attendees.each do |attendee|
        attendee.status = 'canceledfull'
      end
    end
    nil
  end

  def attemdee_params
    case params[:commit]
    when 'Accept'
      'accepted'
    when 'Decline'
      'declined'
    else
      'canceled'
    end
  end
end

app/helpers/attendees_helper.rb
module AttendeesHelper
  def invitations_owner_check(event)
    array = []
    if session[:user_id] == event.user_id
      array.push(render('attendees/inviteform'))
      array.push(render('attendees/invitations'))
    end
    invitation = event.attendees.find_by(user_id: session[:user_id])
    if event.tpeople != event.attendees.where(status: 'accepted').count && !invitation.nil?
      array.push(render('attendees/edit', attendee: invitation)) if invitation.status == 'pending'
      array.push(render('attendees/cancel', attendee: invitation)) if invitation.status == 'accepted'
    end
    array
  end

  def status_messages(event)
    if event.date < Time.now
      flash.now[:notice] =
        'This event is already over'
      return
    elsif event.tpeople == event.attendees.where(status: 'accepted').count
      flash.now[:notice] =
        'This event is not accepting any more people'
      return
    else
      status_events_message(event.attendees.find_by(user_id: session[:user_id]))
    end
    nil
  end

  def status_events_message(invitation)
    case invitation
    when 'accepted'
      flash.now[:notice] =
        'You have already accepted the invitation from this event!'
    when 'declined'
      flash.now[:notice] =
        'You have already declined the invitation from this event!'
    when 'canceled'
      flash.now[:notice] =
        'You have canceled the inviation to this event'
    when 'canceledfull'
      flash.now[:notice] =
        'This event is already full and its not accepting more people'
    end
  end

  def attedees_count(event)
    a_count = event.attendees.where(status: 'accepted')
    return 0 if a_count.nil?

    a_count.count
  end

  def list_group_color(attendee)
    if attendee.event.date.future?
      'list-group-item-success'
    else
      'list-group-item-dark'
    end
  end
end

app/views/attendees/_cancel.html.erb
<div class="d-flex justify-content-around border border-3 rounded p-4 bg-light my-1">
    <p class="text-muted">You can cancel the inviation to his event, but once done this can not be reversed</p>
     <%= form_with model: attendee, url: "#{attendee.event_id}/attendees/#{attendee.id}" do |f| %>
        <div class="d-flex justify-content-center">
            <%= f.text_field :id, value: attendee.id, type: :hidden %>
            <%= f.submit 'Cancel', class:'btn btn-danger mx-2' %>
        </div> 
    <% end %>
</div>

app/views/attendees/_edit.html.erb
<div class="d-flex justify-content-around border border-3 rounded p-4 bg-light my-1">
    <p>You have an invitation to this event</p>
     <%= form_with model: attendee, url: "#{attendee.event_id}/attendees/#{attendee.id}" do |f| %>
        <div class="d-flex justify-content-center">
            <%= f.text_field :id, value: attendee.id, type: :hidden %>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <%= f.submit 'Accept', class:'btn btn-success mx-2' %>
            <%= f.submit 'Decline', class:'btn btn-warning' %>
        </div> 
    <% end %>
</div>

app/views/attendees/_invitations.html.erb
<div class="border border-3 rounded-3 p-1 bg-light my-1">
    <p class="mx-auto text-center">Invitations sent</p>
    <% @event.attendees.order('status ASC').each do |attendees| %>
        <div class="d-flex justify-content-around">
            <p><%= attendees.user.username %></p>
            <p><%= attendees.status %></p>
            <%= link_to 'Delete', user_event_attendee_path(attendees.user_id, attendees.event_id, attendees.id),
                    method: :delete, data: { confirm: 'Are you sure?' },
                    class: 'link-danger mx-2 text-decoration-none' %>
        </div>
    <% end %>
</div>

app/views/attendees/_inviteform.html.erb
<div class="border border-3 rounded-3 p-2 bg-light my-1">
    <p class="mx-auto text-center">Invitations</p>

    <%= form_tag '/invites' do |f| %>
        <div class="row">
            <div class="col-4">
                <%= label_tag "Enter Username", nil,class: "form-label" %>
            </div>
            <div class="col-5">
                <%= text_field_tag (:username), "",class: "form-control", size:"10x3" %>
                <%= text_field_tag :event_id, value = @event.id, type:'hidden' %></div>
            <div class="col-3">
                <%= submit_tag 'Invite', class:"btn btn-primary" %>
            </div>
        </div>
    <% end %>
</div>

app/views/attendees/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-2">

        </div>
        <div class="col-8">
            <div class="container py-2 my-1 text-center">
                <p>Here are all the invitations you got, <%= @user.name %></p>
                <%= link_to 'See upcoming events', user_attendees_path(current_user.id, :time_spec => 'future'), class:'link-success mx-2'%>
                <%= link_to 'See past events', user_attendees_path(current_user.id, :time_spec => 'past'), class:'link-dark mx-2'%>
            </div>
            <div class="list-group">
                <% @attendees.each do |attendee| %>
                    <div class="list-group-item list-group-item-action <%= list_group_color(attendee) %>">
                            <div class="m-1 d-flex justify-content-between border-bottom">
                                <p><%= link_to attendee.event.title, event_path(attendee.event.id), class:'text-decoration-none text-uppercase' %></p>
                                <p><%= attedees_count(attendee.event) %>/<%= attendee.event.tpeople %></p>
                                <p class="text-muted"><%= attendee.event.date %></p>
                            </div>
                            <div class="m-1 d-flex justify-content-between">
                                <p>Status: <%= attendee.status %></p>
                                <p>Organize by: <%= attendee.event.user.username %></p>
                            </div>
                    </div>
                <% end %>
            </div>
        </div>
        <div class="col-2">

        </div>
    </div>
</div>